---
- name: Deploy a jar file
  hosts: all
  remote_user: vaibhav
  tasks:
    - name: Copy jar file to home directory
      copy:
        src: ./target/Calc_main-1.0-SNAPSHOT-jar-with-dependencies.jar
        dest: ~/
    
    
    
